/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.objecte.DTOMessage;
import GUIController.MessagesBearbeitenCtrl;
import javax.swing.JFrame;

/**
 *
 * @author Stefan Dietrich
 */
public class MessagesBearbeiten extends javax.swing.JFrame {

    private MessagesBearbeitenCtrl _ctrl;

    /**
     * Creates new form VeranstaltungKategorie
     */
    public MessagesBearbeiten(MessagesBearbeitenCtrl ctrl) {
        _ctrl = ctrl;
        initComponents();
        loadComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _tblMessages = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        _btnMessageAuswaehlen = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        _btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        _tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titel", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        _tblMessages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(_tblMessages);
        _tblMessages.getColumnModel().getColumn(0).setResizable(false);
        _tblMessages.getColumnModel().getColumn(1).setResizable(false);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, new java.awt.GridBagConstraints());

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel17);

        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jPanel20.setLayout(new java.awt.GridLayout(1, 1));

        _btnMessageAuswaehlen.setText("Auswählen");
        _btnMessageAuswaehlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMessageAuswaehlenActionPerformed(evt);
            }
        });
        jPanel20.add(_btnMessageAuswaehlen);

        jPanel19.add(jPanel20);

        jPanel21.setLayout(new java.awt.GridLayout(1, 1));

        _btnCancel.setText("Cancel");
        _btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnCancelActionPerformed(evt);
            }
        });
        jPanel21.add(_btnCancel);

        jPanel19.add(jPanel21);

        jPanel3.add(jPanel19);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnCancelActionPerformed
        btnCancelClicked();
    }//GEN-LAST:event__btnCancelActionPerformed

    private void _btnMessageAuswaehlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMessageAuswaehlenActionPerformed
        btnMessageWaehlenClicked();
    }//GEN-LAST:event__btnMessageAuswaehlenActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btnCancelClicked();
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnCancel;
    private javax.swing.JButton _btnMessageAuswaehlen;
    private javax.swing.JTable _tblMessages;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadComponents() {
        setTableModel();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void setTableModel() {
        _tblMessages.setModel(_ctrl.getMessageModel());
    }

    private void btnCancelClicked() {
        _ctrl.cancelButton();
    }

    private void btnMessageWaehlenClicked() {
        int selectedRow[] = _tblMessages.getSelectedRows();
        if (selectedRow.length != 0) {
            String title = (String) _tblMessages.getValueAt(selectedRow[0], 0);
            String message = (String) _tblMessages.getValueAt(selectedRow[0], 1);
            _ctrl.selectedMessage(new DTOMessage(title, message, null, ""));
        }
    }

    public void Quit() {
        this.dispose();
    }
    
    public void reloadMessages()
    {
        setTableModel();
    }
}
