/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUIController.MessageSchreibenCtrl;

/**
 *
 * @author Monika
 */
public class MessageSchreiben extends javax.swing.JFrame {
    private MessageSchreibenCtrl _ctrl;
    private String _topic;
    /**
     * Creates new form MessageSchreiben
     */
    public MessageSchreiben(MessageSchreibenCtrl ctrl) {
        _ctrl = ctrl;
        this.setVisible(true);
        initComponents();
        loadComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMessageScreen = new javax.swing.JPanel();
        jPanelScreenHead = new javax.swing.JPanel();
        jlblSreenTitle = new javax.swing.JLabel();
        jlblTopicSelection = new javax.swing.JLabel();
        jPanelTopicAvailable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTopic = new javax.swing.JList();
        jPanelMessagesWrite = new javax.swing.JPanel();
        jPanelMessageTitle = new javax.swing.JPanel();
        jlblMessageTitle = new javax.swing.JLabel();
        jtfMessageTitle = new javax.swing.JTextField();
        jPanelMessageText = new javax.swing.JPanel();
        jlblMessageText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMessageText = new javax.swing.JTextArea();
        jPanelMessageButton = new javax.swing.JPanel();
        jlblInfoMessage = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelMessageScreen.setLayout(new java.awt.GridLayout(3, 2));

        jPanelScreenHead.setLayout(new java.awt.GridLayout(1, 0));

        jlblSreenTitle.setText("Messages erstellen");
        jPanelScreenHead.add(jlblSreenTitle);

        jlblTopicSelection.setText("Bitte Topic auswählen");
        jPanelScreenHead.add(jlblTopicSelection);

        jPanelTopicAvailable.setLayout(new java.awt.GridLayout(1, 0));

        jListTopic.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTopicMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListTopic);

        jPanelTopicAvailable.add(jScrollPane3);

        jPanelScreenHead.add(jPanelTopicAvailable);

        jPanelMessageScreen.add(jPanelScreenHead);

        jPanelMessagesWrite.setLayout(new java.awt.GridLayout(2, 2));

        jPanelMessageTitle.setLayout(new java.awt.GridLayout(1, 2));

        jlblMessageTitle.setText("Message Titel");
        jPanelMessageTitle.add(jlblMessageTitle);
        jPanelMessageTitle.add(jtfMessageTitle);

        jPanelMessagesWrite.add(jPanelMessageTitle);

        jPanelMessageText.setLayout(new java.awt.GridLayout(1, 2));

        jlblMessageText.setText("Message Text");
        jPanelMessageText.add(jlblMessageText);

        jtaMessageText.setColumns(20);
        jtaMessageText.setRows(5);
        jScrollPane1.setViewportView(jtaMessageText);

        jPanelMessageText.add(jScrollPane1);

        jPanelMessagesWrite.add(jPanelMessageText);

        jPanelMessageScreen.add(jPanelMessagesWrite);

        jPanelMessageButton.setLayout(new java.awt.GridLayout(1, 2));
        jPanelMessageButton.add(jlblInfoMessage);

        jbtnSave.setText("Speichern");
        jbtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSaveMouseClicked(evt);
            }
        });
        jPanelMessageButton.add(jbtnSave);

        jbtnCancel.setText("Cancel");
        jbtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCancelMouseClicked(evt);
            }
        });
        jPanelMessageButton.add(jbtnCancel);

        jPanelMessageScreen.add(jPanelMessageButton);

        getContentPane().add(jPanelMessageScreen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCancelMouseClicked
        jbtnCancelClicked();
    }//GEN-LAST:event_jbtnCancelMouseClicked

    private void jbtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaveMouseClicked
        jbtnSaveClicked();
    }//GEN-LAST:event_jbtnSaveMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jbtnCancelClicked();
    }//GEN-LAST:event_formWindowClosing

    private void jListTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTopicMouseClicked
        jListMouseClicked();
    }//GEN-LAST:event_jListTopicMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListTopic;
    private javax.swing.JPanel jPanelMessageButton;
    private javax.swing.JPanel jPanelMessageScreen;
    private javax.swing.JPanel jPanelMessageText;
    private javax.swing.JPanel jPanelMessageTitle;
    private javax.swing.JPanel jPanelMessagesWrite;
    private javax.swing.JPanel jPanelScreenHead;
    private javax.swing.JPanel jPanelTopicAvailable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JLabel jlblInfoMessage;
    private javax.swing.JLabel jlblMessageText;
    private javax.swing.JLabel jlblMessageTitle;
    private javax.swing.JLabel jlblSreenTitle;
    private javax.swing.JLabel jlblTopicSelection;
    private javax.swing.JTextArea jtaMessageText;
    private javax.swing.JTextField jtfMessageTitle;
    // End of variables declaration//GEN-END:variables
    
     private void loadComponents() {
        setListModel();
    }
    
    private void setListModel() {
        jListTopic.setModel(_ctrl.getTopicModel());
    }
    
     private void jListMouseClicked() {
        _topic = jListTopic.getSelectedValue().toString();
        System.out.println(_topic);
    }

    private void jbtnSaveClicked() {
        String title = jtfMessageTitle.getText();
        String text = jtaMessageText.getText();
        if (!title.isEmpty() || !text.isEmpty()) {
            _ctrl.createMessage(title, text, _topic);
        } else {
            jlblInfoMessage.setText("Bitte geben Sie Titel und Text ein.");
        }
    }

     public void Quit() {
        this.dispose();
    }

    private void jbtnCancelClicked() {
        _ctrl.CancelButtonClicked();
    }
}
