/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUIController.VeranstaltungsSuchenCtrl;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.util.List;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Monika
 */
public class VeranstaltungSuchen extends javax.swing.JFrame {

    private VeranstaltungsSuchenCtrl ctrl;
    private int veranstId;
    private List<Object[]> tempVeranstInfoList = new LinkedList();

    /**
     * Creates new form VeranstaltungSuchen
     */
    public VeranstaltungSuchen(VeranstaltungsSuchenCtrl controller) {
        initComponents();
        this.setVisible(true);
        ctrl = controller;
        loadComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreen = new javax.swing.JPanel();
        jPanelScreenTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        _btnMessage = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanelEventSearch = new javax.swing.JPanel();
        jPanelSearchLabels = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelArtist = new javax.swing.JLabel();
        jPanelSearchButton = new javax.swing.JPanel();
        jPanelSearchInput = new javax.swing.JPanel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldPlace = new javax.swing.JTextField();
        jTextFieldArtist = new javax.swing.JTextField();
        jPanelDeleteSearchButton = new javax.swing.JPanel();
        jButtonSearchStart = new javax.swing.JButton();
        jPanelSearchDelete = new javax.swing.JPanel();
        jButtonSearchDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelEventTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeranstaltungen = new javax.swing.JTable();
        jPanelSelectBack = new javax.swing.JPanel();
        jPaneSelect = new javax.swing.JPanel();
        jPanelBackButton = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jButtonAnzeigen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanelScreen.setLayout(new java.awt.GridLayout(5, 1));

        jPanelScreenTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setText("Veranstaltung suchen");
        jPanelScreenTitle.add(jLabel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(2, 2));

        _btnMessage.setBackground(new java.awt.Color(255, 255, 255));
        _btnMessage.setText("M");
        _btnMessage.setEnabled(false);
        _btnMessage.setMaximumSize(new java.awt.Dimension(10, 10));
        _btnMessage.setMinimumSize(new java.awt.Dimension(10, 10));
        _btnMessage.setPreferredSize(new java.awt.Dimension(10, 10));
        _btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMessageActionPerformed(evt);
            }
        });
        jPanel10.add(_btnMessage);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11);

        jPanel7.add(jPanel10);

        jPanel6.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8);

        jPanel4.add(jPanel6);

        jPanel2.add(jPanel4);

        jPanelScreenTitle.add(jPanel2);

        jPanelScreen.add(jPanelScreenTitle);

        jPanelEventSearch.setLayout(new java.awt.GridLayout(2, 4));

        jPanelSearchLabels.setLayout(new java.awt.GridLayout(1, 1));

        jLabelDate.setText("Datum");
        jPanelSearchLabels.add(jLabelDate);

        jLabelName.setText("Veranstaltungsort");
        jPanelSearchLabels.add(jLabelName);

        jLabelArtist.setText("Künstler");
        jPanelSearchLabels.add(jLabelArtist);

        jPanelSearchButton.setLayout(new java.awt.GridLayout(1, 1));
        jPanelSearchLabels.add(jPanelSearchButton);

        jPanelEventSearch.add(jPanelSearchLabels);

        jPanelSearchInput.setLayout(new java.awt.GridLayout(1, 5));
        jPanelSearchInput.add(jTextFieldDate);
        jPanelSearchInput.add(jTextFieldPlace);
        jPanelSearchInput.add(jTextFieldArtist);

        jPanelDeleteSearchButton.setLayout(new java.awt.GridLayout(1, 1));

        jButtonSearchStart.setText("Suchen");
        jButtonSearchStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchStartActionPerformed(evt);
            }
        });
        jPanelDeleteSearchButton.add(jButtonSearchStart);

        jPanelSearchInput.add(jPanelDeleteSearchButton);

        jPanelSearchDelete.setLayout(new java.awt.GridLayout(1, 0));

        jButtonSearchDelete.setText("Eingabe löschen");
        jButtonSearchDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDeleteActionPerformed(evt);
            }
        });
        jPanelSearchDelete.add(jButtonSearchDelete);

        jPanelSearchInput.add(jPanelSearchDelete);

        jPanelEventSearch.add(jPanelSearchInput);

        jPanelScreen.add(jPanelEventSearch);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanelScreen.add(jPanel1);

        jPanelEventTable.setLayout(new java.awt.GridLayout(1, 1));

        jTableVeranstaltungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Datum", "Name", "Ort", "Künstler", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeranstaltungen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableVeranstaltungen.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableVeranstaltungen);

        jPanelEventTable.add(jScrollPane1);

        jPanelScreen.add(jPanelEventTable);

        jPanelSelectBack.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPaneSelectLayout = new javax.swing.GroupLayout(jPaneSelect);
        jPaneSelect.setLayout(jPaneSelectLayout);
        jPaneSelectLayout.setHorizontalGroup(
            jPaneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPaneSelectLayout.setVerticalGroup(
            jPaneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanelSelectBack.add(jPaneSelect);

        jButtonBack.setText("Cancel");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonAnzeigen.setText("Veranstaltung anzeigen");
        jButtonAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnzeigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackButtonLayout = new javax.swing.GroupLayout(jPanelBackButton);
        jPanelBackButton.setLayout(jPanelBackButtonLayout);
        jPanelBackButtonLayout.setHorizontalGroup(
            jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackButtonLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jButtonAnzeigen)
                .addGap(54, 54, 54)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBackButtonLayout.setVerticalGroup(
            jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackButtonLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelSelectBack.add(jPanelBackButton);

        jPanelScreen.add(jPanelSelectBack);

        getContentPane().add(jPanelScreen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDeleteActionPerformed
        btnSearchDeleteClicked();
    }//GEN-LAST:event_jButtonSearchDeleteActionPerformed

    private void jButtonSearchStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchStartActionPerformed
        btnSearchStartClicked();
    }//GEN-LAST:event_jButtonSearchStartActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        btnBackClicked();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnzeigenActionPerformed
        veranstaltungAnzeigen();
    }//GEN-LAST:event_jButtonAnzeigenActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btnBackClicked();
    }//GEN-LAST:event_formWindowClosing

    private void _btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMessageActionPerformed
        btnMessageClicked();
    }//GEN-LAST:event__btnMessageActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnMessage;
    private javax.swing.JButton jButtonAnzeigen;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSearchDelete;
    private javax.swing.JButton jButtonSearchStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPaneSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBackButton;
    private javax.swing.JPanel jPanelDeleteSearchButton;
    private javax.swing.JPanel jPanelEventSearch;
    private javax.swing.JPanel jPanelEventTable;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelScreenTitle;
    private javax.swing.JPanel jPanelSearchButton;
    private javax.swing.JPanel jPanelSearchDelete;
    private javax.swing.JPanel jPanelSearchInput;
    private javax.swing.JPanel jPanelSearchLabels;
    private javax.swing.JPanel jPanelSelectBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeranstaltungen;
    private javax.swing.JTextField jTextFieldArtist;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldPlace;
    // End of variables declaration//GEN-END:variables

    private void loadComponents() {
        setTableModel();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        checkMessages();
    }

    public void btnSearchStartClicked() {
        String date = jTextFieldDate.getText();
        String place = jTextFieldPlace.getText();
        String artist = jTextFieldArtist.getText();
        if (date.isEmpty()) {
            date = null;
        }
        if (place.isEmpty()) {
            place = null;
        }
        if (artist.isEmpty()) {
            artist = null;
        }
        ctrl.searchingForEvents(date, place, artist);
        System.out.println(date + "," + place + "," + artist);
        setTableModel();
    }

    private void btnSearchDeleteClicked() {
        jTextFieldDate.setText("");
        jTextFieldPlace.setText("");
        jTextFieldArtist.setText("");
    }

    private void btnBackClicked() {
        ctrl.CancelClicked();
    }

    private void setTableModel() {
        jTableVeranstaltungen.setModel(ctrl.getVeranstaltungInfoModel());
        jTableVeranstaltungen.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                TableModel model = (TableModel) e.getSource();
                Object[] changedRow = new Object[model.getColumnCount()];
                for (int i = 0; i < changedRow.length; i++) {
                    changedRow[i] = model.getValueAt(row, i);
                }
            }
        });
    }

    private void veranstaltungAnzeigen() {
        int row = jTableVeranstaltungen.getSelectedRow();
        if (row != -1) {
            int vno = (Integer) jTableVeranstaltungen.getValueAt(row, 4);
            ctrl.VeranstaltungAnzeigen(vno);
        }
    }

    public void Quit() {
        this.dispose();
    }

    private void btnMessageClicked() {
        ctrl.MessageClicked();
    }

    private void newMessage() {
        _btnMessage.setEnabled(true);
        _btnMessage.setForeground(Color.RED);
        _btnMessage.setFont(new Font(Font.DIALOG, Font.BOLD, Font.BOLD));
    }

    public void checkMessages() {
        if (ctrl.getMessage() != null) {
            newMessage();
        } else {
            _btnMessage.setEnabled(false);
            _btnMessage.setForeground(Color.GRAY);
            _btnMessage.setFont(null);
        }
    }
}
